### ISSUE TITLE
sample 运行报错

### ISSUE THREAD

**Issue by aoyang-hd** [hellloxiaotian/PSDNet#5]
(torch3d_ay) cv@amax:/data/cv/aoyang/DSRNet-main/DSRNet$ python sample.py 
Traceback (most recent call last):
  File "/data/cv/aoyang/DSRNet-main/DSRNet/sample.py", line 221, in <module>
    main(cfg)
  File "/data/cv/aoyang/DSRNet-main/DSRNet/sample.py", line 203, in main
    net = module.Net(cfg)
TypeError: __init__() takes 1 positional argument but 2 were given

非常感谢您能来帮我解答问题

**Comment by hellloxiaotian** [comment]
We have updated the relevant files and annotation. Thank you for your attention.
