### ISSUE TITLE
problem with size of tensors

### ISSUE THREAD

**Issue by VasoKat** [hellloxiaotian/PSDNet#6]
When i run the train.py with scale=2 it shows me the following error.Even if i use differrent scale it shows the error.

/home/vasiliki/anaconda3/envs/my-env/lib/python3.10/site-packages/torch/nn/modules/loss.py:536: UserWarning: Using a target size (torch.Size([64, 3, 128, 128])) that is different to the input size (torch.Size([64, 3, 64, 64])). This will likely lead to incorrect results due to broadcasting. Please ensure they have the same size.
  return F.mse_loss(input, target, reduction=self.reduction)
Traceback (most recent call last):
  File "/home/vasiliki/Επιφάνεια εργασίας/DSRNet-main/DSRNet/train.py", line 50, in <module>
    main(cfg)
  File "/home/vasiliki/Επιφάνεια εργασίας/DSRNet-main/DSRNet/train.py", line 46, in main
    solver.fit()
  File "/home/vasiliki/Επιφάνεια εργασίας/DSRNet-main/DSRNet/solver.py", line 91, in fit
    loss = self.loss_fn(sr, hr)
  File "/home/vasiliki/anaconda3/envs/my-env/lib/python3.10/site-packages/torch/nn/modules/module.py", line 1501, in _call_impl
    return forward_call(*args, **kwargs)
  File "/home/vasiliki/anaconda3/envs/my-env/lib/python3.10/site-packages/torch/nn/modules/loss.py", line 536, in forward
    return F.mse_loss(input, target, reduction=self.reduction)
  File "/home/vasiliki/anaconda3/envs/my-env/lib/python3.10/site-packages/torch/nn/functional.py", line 3294, in mse_loss
    expanded_input, expanded_target = torch.broadcast_tensors(input, target)
  File "/home/vasiliki/anaconda3/envs/my-env/lib/python3.10/site-packages/torch/functional.py", line 74, in broadcast_tensors
    return _VF.broadcast_tensors(tensors)  # type: ignore[attr-defined]
RuntimeError: The size of tensor a (64) must match the size of tensor b (128) at non-singleton dimension 3

**Comment by hellloxiaotian** [comment]
We suggest that you should check if the size of the input image is half that of the GT image.

**Comment by VasoKat** [comment]
> We suggest that you should check if the size of the input image is half that of the GT image.

For scale=2 the input image is half that of the GT image and for the other scales (x3,x4) τhe size of the input images is correct. This error is shown for all the scales. I downloaded the DIV2K dataset from the link you have.

**Comment by hellloxiaotian** [comment]
Thank you for your attention.
If so, I cannot see problem from your description. This code goes well on our device.
You can print the tensor size after every convolution to try to solve this problem. 
Wish everything goes well.
